version: "3.8"

services:
  dotnet.questions:
    build:
      context: RuOverflow.Questions/
      dockerfile: ./RuOverflow.Questions/Dockerfile
    ports:
      - "11001:80"
    restart: on-failure
    environment:
      - RuOverFlow_Question_ConnectionString=Host=postgres;Database=ruflow;User Id=postgres;Password=postgres;Port=5432;
      - RedisUrl=redis:6379
    depends_on:
      - redis
      - postgres
      - zoo1
      - kafka1
      - kafka2
      - kafka3
  background:
    build:
      context: Background/
      dockerfile: ./Background/Dockerfile
    environment:
      - RuOverFlow_Question_ConnectionString=Host=postgres;Database=ruflow;User Id=postgres;Password=postgres;Port=5432;
    depends_on:
      - postgres
      - zoo1
      - kafka1
      - kafka2
      - kafka3
      - debezium
      - dotnet.questions
  gqluserservice:
    build:
      context: GqlUserService/
      dockerfile: ./Dockerfile
    ports:
      - "50071:50071"
    depends_on:
      - mssql
  redis:
    container_name: "redis"
    image: "redis"
    hostname: redis
    command: >
      --maxmemory 1073741824
      --maxmemory-policy allkeys-lru
      --loglevel warning
      --rdbchecksum no
    ports:
      - "6378:6379"
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    user: root
    ports:
      - "1400:1433"
    volumes:
      - mssql-server-linux-data:/var/opt/mssql/data
    environment:
      SA_PASSWORD: "Password123"
      ACCEPT_EULA: "Y"
  postgres:
    image: debezium/postgres:14
    env_file:
      - ./RuOverflow.Questions/RuOverflow.Questions/postgres.env
    volumes:
      - postgres:/var/opt/postgres/data
    ports:
      - "5433:5432"
  debezium-setup:
    build:
      context: ./DebeziumSetup
      dockerfile: ./Dockerfile
    restart: on-failure
    depends_on:
      - background
      - debezium
  debezium:
    image: debezium/connect:1.9
    environment:
      BOOTSTRAP_SERVERS: kafka1:19092,kafka1:19093,kafka1:19094
      GROUP_ID: 1
      CONFIG_STORAGE_TOPIC: debezium_config
      OFFSET_STORAGE_TOPIC: debezium_offset
      STATUS_STORAGE_TOPIC: docker-connect-debezium-status
      KEY_CONVERTER: org.apache.kafka.connect.storage.StringConverter
      VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      LOG_LEVEL: ERROR
    depends_on:
      - kafka1
      - kafka2
      - kafka3
      - postgres
    ports:
      - "8083:8083"
  akhq:
    image: tchiotludo/akhq
    environment:
      AKHQ_CONFIGURATION: |
        akhq:
          connections:
            docker-kafka-server:
              properties:
                bootstrap.servers: "kafka1:19092,kafka2:19093,kafka3:19094"
              connect:
                - name: "debezium"
                  url: "http://debezium:8083"
    ports:
      - "8081:8080"
    links:
      - kafka1
      - kafka2
      - kafka3
      - debezium
  zoo1:
    image: confluentinc/cp-zookeeper:7.0.1
    hostname: zoo1
    container_name: zoo1
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_SERVERS: zoo1:2888:3888
  kafka1:
    image: confluentinc/cp-kafka:7.0.1
    hostname: kafka1
    restart: always
    container_name: kafka1
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://kafka1:19092,LISTENER_DOCKER_EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: "zoo1:2181"
      KAFKA_BROKER_ID: 1
      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
      KAFKA_AUTHORIZER_CLASS_NAME: kafka.security.authorizer.AclAuthorizer
      KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND: "true"
    depends_on:
      - zoo1
  kafka2:
    image: confluentinc/cp-kafka:7.0.1
    hostname: kafka2
    restart: always
    container_name: kafka2
    ports:
      - "9093:9093"
    environment:
      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://kafka2:19093,LISTENER_DOCKER_EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: "zoo1:2181"
      KAFKA_BROKER_ID: 2
      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
      KAFKA_AUTHORIZER_CLASS_NAME: kafka.security.authorizer.AclAuthorizer
      KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND: "true"
    depends_on:
      - zoo1
  kafka3:
    image: confluentinc/cp-kafka:7.0.1
    hostname: kafka3
    restart: always
    container_name: kafka3
    ports:
      - "9094:9094"
    environment:
      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://kafka3:19094,LISTENER_DOCKER_EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: "zoo1:2181"
      KAFKA_BROKER_ID: 3
      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
      KAFKA_AUTHORIZER_CLASS_NAME: kafka.security.authorizer.AclAuthorizer
      KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND: "true"
    depends_on:
      - zoo1
  elasticsearch1:
    image: elasticsearch:8.1.3
    environment:
      - network.host=0.0.0.0
      - node.name=elasticsearch1
      - discovery.type=single-node
      - cluster.name=RuOverflow-cluster
      - xpack.license.self_generated.type=basic
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
    volumes:
      - es01:/usr/share/elasticsearch/data
  kibana:
    image: kibana:8.1.3
    container_name: kibana
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch1:9200
      SERVER_HOSTS: 0.0.0.0
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch1
  auth:
    environment:
      - ASPNETCORE_URLS=http://+:5200
      - ASPNETCORE_ENVIRONMENT=Development
    env_file:
      - ./Auth/auth/Auth.Web/postgres.env
    depends_on:
      - auth-db
    build:
      context: ./Auth/auth/Auth.Web
      dockerfile: ./Dockerfile
    ports:
      - "5200:5200"
  auth-db:
    image: postgres:14
    env_file:
      - ./Auth/auth/Auth.Web/postgres.env
    volumes:
      - auth-db:/var/lib/postgresql/data:rw
    ports:
      - "5435:5432"
  apollo-gql-express:
    environment:
      - node --max-old-space-size=4096 start.js
    build: /apollo-gql-express
      context: ./apollo-gql-express
      dockerfile: Dockerfile
    volumes:
      - .:/apollo-gql-express
      - /apollo-gql-express/node_modules
    container_name: docker-node-mongo
    ports:
      - "4000:4000"
    command: npm start
    external_links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - mongo:/var/lib/mongo/data
    ports:
      - "27017:27017"

volumes:
  mssql-server-linux-data:
  postgres:
  es01:
  auth-db:
